[package]
name = "gcode_respiralizer_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kiddo = "3.0.0"
rand = "0.8.5"
regex = "1.10.2"
ordered-float = "4.2.0"
merging-iterator = "1.3.0"
