[package]
name = "gcode_respiralizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gcode_respiralizer_lib = { path = "../gcode_respiralizer_lib" }
