#!/bin/bash
set -e
clear
if [ $# -eq 0 ]
  then
    echo "usage:"
    echo "misc_test <folder_name>"
    exit 1
fi
folder_name=$1
cargo run --release -- /c/stuff/gr_test/${folder_name}/fine_0.03mm_PETG_MK3S.gcode /c/stuff/gr_test/${folder_name}/coarse_0.3mm_PETG_MK3S.gcode /c/stuff/gr_test/${folder_name}/OUTPUT.gcode
